// Generated by scripts/build-dist.mjs. Source defaults to store.
(function (root) {
  'use strict';
  const channel = 'store';
  root.__XVM_BUILD_CHANNEL__ = channel;
  root.__xvmBuildChannel = channel;
  root.__xvmIsCommunityDevBuild = channel === 'community-dev';
})(typeof globalThis !== 'undefined' ? globalThis : window);
